### ISSUE TITLE
 production.ERROR: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by SMEWebify** [SMEWebify/WebErpMesv2#174]
[2023-07-20 05:29:17] production.ERROR: Trying to access array offset on value of type null {"view":{"view":"/homepages/10/d912969182/htdocs/demo/resources/views/print/pdf-purchases.blade.php","data":[]},"userId":1,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Trying to access array offset on value of type null at /homepages/10/d912969182/htdocs/demo/resources/views/print/pdf-purchases.blade.php:70)
[stacktrace]
#0 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /homepages/10/d912969182/htdocs/demo/resources/views/print/pdf-purchases.blade.php(70): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('/homepages/10/d...')

**Comment by SMEWebify** [comment]
Debug Binding :

SELECT * FROM `companies_contacts` WHERE `companies_contacts`.`id` = 0 limit 1

**Comment by SMEWebify** [comment]
```
$PurchaseOrderCreated = Purchases::create([
                    'code'=>$this->code,  
                    'label'=>$this->label, 
                    'companies_id'=>$this->companies_id,   
                    'user_id'=>$this->user_id,
                ]);
```
