### ISSUE TITLE
Column not found: 1054 Unknown column 'orders.id' in 'order clause

### ISSUE THREAD

**Issue by SMEWebify** [SMEWebify/WebErpMesv2#177]
[2023-08-05 10:06:51] production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'orders.id' in 'order clause' (SQL: select * from `delivery_lines` where (`invoice_status` = 1 or `invoice_status` = 2) and exists (select * from `deliverys` where `delivery_lines`.`deliverys_id` = `deliverys`.`id` and `companies_id` like %26%) order by `orders`.`id` asc) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'orders.id' in 'order clause' (SQL: select * from `delivery_lines` where (`invoice_status` = 1 or `invoice_status` = 2) and exists (select * from `deliverys` where `delivery_lines`.`deliverys_id` = `deliverys`.`id` and `companies_id` like %26%) order by `orders`.`id` asc) at /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#1 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run()
#2 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2656): Illuminate\\Database\\Connection->select()
#3 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2644): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3180): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2645): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): Illuminate\\Database\\Query\\Builder->get()
#7 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels()
#8 /homepages/10/d912969182/htdocs/demo/app/Http/Livewire/InvoicesRequest.php(85): Illuminate\\Database\\Eloquent\\Builder->get()
#9 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\InvoicesRequest->render()
#10 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\\Container\\BoundMethod::call()
#14 /homepages/10/d912969182/htdocs/demo/vendor/livewire/livewire/src/Component.php(173): Illuminate\\Container\\Container->call()
#15 /homepages/10/d912969182/htdocs/demo/vendor/livewire/livewire/src/LifecycleManager.php(131): Livewire\\Component->renderToView()
#16 /homepages/10/d912969182/htdocs/demo/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(14): Livewire\\LifecycleManager->renderToView()
#17 /homepages/10/d912969182/htdocs/demo/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(20): Livewire\\Connection\\ConnectionHandler->handle()
#18 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#19 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#20 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#21 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#22 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#23 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#25 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#27 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#29 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#31 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#32 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#34 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#36 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#38 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#39 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#40 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#41 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#42 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#43 /homepages/10/d912969182/htdocs/demo/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#45 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#47 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#49 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#51 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#53 /homepages/10/d912969182/htdocs/demo/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#55 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#57 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#59 /homepages/10/d912969182/htdocs/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#60 /homepages/10/d912969182/htdocs/demo/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()

**Comment by SMEWebify** [comment]
Same to SMEWebify/WebErpMesv2/issues/176
